name: Deploy

on:
  push:
    branches:
      - master

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
    steps:
      - uses: actions/checkout@v2
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      # - run: cd backend && cargo build --verbose --release
      - run: mkdir -p backend/target/release && echo "testy" > backend/target/release/mafi
      # - run: echo ${{ secrets.DEPLOY_AUTHKEY }} > /tmp/private_key
      - run: echo "hello world" > /tmp/hello
      - run: cat /tmp/hello
      - name: Copy files to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          key_path: /tmp/private_key
          source: "backend/target/release/mafi"
          target: "~/mafi"
