name: Deploy

on:
  push:
    branches:
      - master

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    environment: default
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
    steps:
      - uses: actions/checkout@v2
      # - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      # - run: cd backend && cargo build --verbose --release
      - run: mkdir -p backend/target/release && echo "testy13" > backend/target/release/mafi # DELETE ME WHEN DONE TESTING
      - name: Copy files to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          key: ${{ secrets.DEPLOY_AUTHKEY }}
          source: "backend/target/release/mafi"
          target: "~/mafi"
