name: Deploy

on:
  push:
    branches:
      - master

env: 
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    name: Deploy to remote
    environment: default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare the rust compiler
        run: rustup update nightly && rustup default nightly
      - name: Build backend
        run: cd backend && cargo build --verbose --release
      - name: Copy backend files to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_AUTHKEY }}
          source: "backend/target/release/mafi"
          target: "~/"
          strip_components: 3
      
      - name: Prepare npm
        uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Install frontend dependencies
        run: cd web && npm install && npm run build
      - name: Copy frontend files to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_AUTHKEY }}
          source: "web"
          target: "~/"

      - name: Restart services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_AUTHKEY }}
          script: |
            chmod +x ~/mafi \
              && echo ${{ secrets.DEPLOY_PASSWORD }} | sudo -S systemctl restart mafi-backend \
              && echo ${{ secrets.DEPLOY_PASSWORD }} | sudo -S systemctl restart mafi-frontend
